### ISSUE TITLE
pufferfish for assembly

### ISSUE THREAD

**Issue by SilasK** [COMBINE-lab/pufferfish#3]
Hello, your project seems very interesting. 

Is it already possible to use it for assembly? If yes could you give me a hint where to start?

**Comment by fataltes** [comment]
Hi Silask,

Thanks for your interest.

I know it is probably so late and I really apologize for not replying sooner. 

Pufferfish is basically designed as an index data structure on a set of *known* references plus the api required to query the set for a short sequencing read.  Unfortunately, that means it is likely not useful to you for the purposes of assembly. It's basically an index designed for mapping/aligning short read sequences against a set of references --- and will also eventually be useful for assembly comparison (i.e. comparing references in terms of their De Bruijn graph paths).  However, pufferfish does not, itself, perform any assembly.

--
Fatemeh
