### ISSUE TITLE
Pufferfish index decoy option fixFasta doesn't recognize FASTA header(s) and fails

### ISSUE THREAD

**Issue by hermidalc** [COMBINE-lab/pufferfish#37]
I tried to load the latest [GENCODE human genome FASTA](https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/latest_release/GRCh38.primary_assembly.genome.fa.gz) as a decoy into pufferfish index and the `fixFasta` component immediately give the following error:
```
[2022-08-19 14:27:01.875] [puff::index::jointLog] [info] Running fixFasta
[2022-08-19 14:27:01.875] [puff::index::jointLog] [critical] The decoy name NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN was encountered more than once --- please ensure all decoy names and sequences are unique.
[2022-08-19 14:27:01.875] [puff::index::jointLog] [error] The fixFasta phase failed with exit code 1
```
Even though the genome file head looks like this:
```
$ head -10 GRCh38.primary_assembly.genome.fa
>chr1 1
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
```
I first thought it was the leading `N`s but even after clipping all leading and trailing `N`s in all sequence entries it still gives the same error with the first sequence. It appears that when processing the decoy FASTA file fixFasta has a bug, because it doesn't notice the `>` header(s).

**Comment by rob-p** [comment]
Hi @hermidalc,

  The decoy sequence itself should be included at the *end* of the normal input reference fasta.  The decoy file instead contains the *names* of the decoy records in the reference file. The error you are seeing is because its interpreting the fasta header as a name and that record isn't found in the normal reference file.

**Comment by hermidalc** [comment]
Ok thank you @rob-p that makes sense! Closing
