### ISSUE TITLE
Pufferfish Dependency: Need Help

### ISSUE THREAD

**Issue by ruhulsbu** [COMBINE-lab/pufferfish#4]
It seems the pufferfish is dependant on json, SeqLib, htslib etc. 

I installed json and SeqLib, and also downloaded htslib, 

Now while building it, I am stuck with the following error: 

gcc -shared -Wl,-soname,libhts.so.2   -o libhts.so kfunc.pico knetfile.pico kstring.pico bcf_sr_sort.pico bgzf.pico errmod.pico faidx.pico hfile.pico hfile_net.pico hts.pico hts_os.pico md5.pico multipart.pico probaln.pico realn.pico regidx.pico sam.pico synced_bcf_reader.pico vcf_sweep.pico tbx.pico textutils.pico thread_pool.pico vcf.pico vcfutils.pico cram/cram_codecs.pico cram/cram_decode.pico cram/cram_encode.pico cram/cram_external.pico cram/cram_index.pico cram/cram_io.pico cram/cram_samtools.pico cram/cram_stats.pico cram/files.pico cram/mFILE.pico cram/open_trace_file.pico cram/pooled_alloc.pico cram/rANS_static.pico cram/sam_header.pico cram/string_alloc.pico -llzma -lbz2 -lz -lm   -lpthread
/usr/bin/ld: /gpfs/software/bzip2-1.0.6/lib/libbz2.a(bzlib.o): relocation R_X86_64_32S against `BZ2_crc32Table' can not be used when making a shared object; recompile with -fPIC
/gpfs/software/bzip2-1.0.6/lib/libbz2.a: could not read symbols: Bad value

Is there a stable release of cedar that I can obtain?

**Comment by fataltes** [comment]
Hi Ruhul,

It looks like that this particular problem should be resolved by recompiling `libbz2` with `-fPIC` flag.

Also, one thing that might be helpful in general is that these libraries that pufferfish/cedar are dependent on should also be compiled with the same gcc version (and c++ flags). 

unfortunately, we don't have release version for cedar yet, so I apologize that you have to deal with the
 unstable version in cedar branch. But I expect after fully compiling the project, you can rely on the results you get running cedar.

do you think that a docker image could help speed up your installation time?
