### ISSUE TITLE
Performance - WFE is used in incorrect scenario for aarch64 cpuRelax

### ISSUE THREAD

**Issue by dslarm** [COMBINE-lab/pufferfish#48]
The WFE instruction is used in cpuRelax (include/FastxParserThreadUtils.hpp) for aarch64.

Using WFE stalls the core, but from an O/S perspective the thread is still running, so the thread is not swapped out by the O/S to do more useful work.

Whenever running where number of cores == number of worker threads (such as a Salmon typical usage), this means the worker threads are not getting scheduled on that stalled core.  

It is very impacting at lower thread counts: the quick solution is replacing WFE with the aarch64 "yield" - which is already an unreachable (for aarch64) code block further down in the existing cpuRelax implementation's #defines - so basically just deleting the wfe section.  This improves performance of a 4-core Graviton3 whilst running 4-threads of Salmon (quant) by about 11%. 

It may be worth considering if this assembler block as a whole is delivering sufficient benefit across all architectures. Replacing with nanosleep of between 200 and 2000ns and allowing the O/S to deal with yielding cores appropriately - made approx 1% difference to the run time across Genoa, Graviton3, Graviton4 and Sapphire Rapids - compared with the existing (or 'yield' for aarch64) path, for the 4 or 8 cores I ran on with 4 or 8 threads.  It'd be worth seeing if there were any difference at larger core count and tuning that delay time - there are potential differences in impact for whether SMT is on or off for the x86 platforms to measure too.

**Comment by rob-p** [comment]
Hi @dslarm,

  I've moved this over into the FQFeeder repository, which is the parser that is vendored here.  I'd prefer to fix this upstream and then update the dependencies here.

--Rob
