### ISSUE TITLE
fixfasta binary

### ISSUE THREAD

**Issue by genomax** [COMBINE-lab/pufferfish#5]
@fataltes and @rob-p 

Rob asked me to create an issue to see if you could make a pre-compiled binary for "fixfasta" program that is part of your pufferfish package. 

Thanks in advance!

**Comment by rob-p** [comment]
Tagging @k3yavi as well.  Thanks guys!

**Comment by k3yavi** [comment]
Hi @genomax ,
Thanks for raising the issue.
We surely can help you with the pre-compiled binary, but before that can we know what OS and the version you are using for your experiments ?

**Comment by genomax** [comment]
CentOS would be fine.

**Comment by k3yavi** [comment]
Cool, we are working on generating the binary. Will update you soon ..

**Comment by fataltes** [comment]
Hi @genomax ,

I've pushed a binary for fixedFasta to develop branch under the folder named "bin" ([here](https://github.com/COMBINE-lab/pufferfish/tree/develop/bin)) that has been compiled and linked with/to static libraries on a system with ubuntu 16.10 as the OS.
As much as I know, the statically compiled binaries should be compatible with different distributions of linux.

So please try and see if it works on your system or not.

Thank you,
Fatemeh

**Comment by genomax** [comment]
Thanks Fatemeh.
